'use strict';
/* Mobile capture, editable catalogues and optional browser dictation. */
const CHOICE_LABELS={product:'Bike type',type:'Type',appVersion:'Applicability version',mark:'Mark',speed:'Speed',variants:'Variants',line:'Line / station',reason:'Reason'};
const CHOICE_DEFAULTS={product:['All'],type:['All'],appVersion:['All'],mark:[],speed:['-'],variants:['-'],line:[],reason:['First Issue']};
function uniqueChoices(values){return [...new Set(values.filter(v=>typeof v==='string').map(v=>v.trim()).filter(v=>v&&v!=='__add_choice__'))].slice(0,200)}
function normaliseChoices(){settings.areas=uniqueChoices([...(Array.isArray(settings.areas)?settings.areas:[]),...AREAS,...Object.keys(settings.areaCodes||{})]);const given=settings.choices||{};settings.choices=Object.fromEntries(Object.keys(CHOICE_LABELS).map(k=>[k,uniqueChoices(Array.isArray(given[k])?given[k]:CHOICE_DEFAULTS[k])]));}
function areaNames(current=''){return uniqueChoices([...(settings.areas||AREAS),...Object.keys(settings.areaCodes||{}),current])}
function fillChoice(el,key,current=''){el.innerHTML='<option value="">Choose…</option>'+uniqueChoices([...(settings.choices?.[key]||CHOICE_DEFAULTS[key]||[]),current]).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')+'<option value="__add_choice__">＋ Add a choice…</option>';el.value=current}
function codeOptions(el,current=''){el.innerHTML='<option value="">Set a code in Settings</option>'+uniqueChoices([...Object.values(settings.areaCodes||{}),current]).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');el.value=current}
function choiceSettingsUI(){normaliseChoices();$('#choice-settings').innerHTML=Object.entries(CHOICE_LABELS).map(([k,label])=>`<label>${label}<textarea data-choice-setting="${k}" rows="4">${esc(settings.choices[k].join('\n'))}</textarea></label>`).join('');$('#add-area').onclick=async()=>{const name=$('#new-area-name').value.trim(),code=$('#new-area-code').value.trim().toUpperCase();if(!name||['__proto__','constructor','prototype'].includes(name)||!/^[A-Z0-9]{1,8}$/.test(code)){toast('Enter an area name and a code of 1–8 letters or numbers.');return}if(areaNames().some(a=>a.toLowerCase()===name.toLowerCase())){toast('That area already exists. Edit its code above.');return}settings.areas.push(name);settings.areaCodes[name]=code;try{await saveSettings();$('#new-area-name').value='';$('#new-area-code').value='';settingsUI();$('#area-settings-status').textContent='Area added. It is now available in new and existing documents.'}catch{toast('Could not save the new area.')}};$('#save-choices').onclick=async()=>{for(const el of $$('[data-choice-setting]'))settings.choices[el.dataset.choiceSetting]=uniqueChoices(el.value.split('\n'));try{await saveSettings();$('#choice-settings-status').textContent='Choices saved. Existing documents keep their selected values.'}catch{toast('Could not save choices.')}}}
function exportChoices(){normaliseChoices();return {areas:[...settings.areas],areaCodes:{...settings.areaCodes},choices:structuredClone(settings.choices)}}
function mergeChoices(config){if(!config||typeof config!=='object')return;const codes=Object.entries(config.areaCodes||{}).filter(([k,v])=>k.length<=80&&typeof v==='string'&&/^[A-Z0-9]{0,8}$/.test(v));settings.areaCodes={...settings.areaCodes,...Object.fromEntries(codes)};settings.areas=uniqueChoices([...(settings.areas||[]),...(Array.isArray(config.areas)?config.areas:[])]);for(const k of Object.keys(CHOICE_LABELS))if(Array.isArray(config.choices?.[k]))settings.choices[k]=uniqueChoices([...(settings.choices[k]||[]),...config.choices[k]]);normaliseChoices()}
let edZoom=1;
function markNoteSummary(){const m=selMark();$('#edit-mark-note').textContent=m&&['text','torque'].includes(m.type)?'Edit text':'Edit note';$('#mark-note-summary').textContent=m?(m.text||m.note||'No note yet'):''}
function editorZoom(value){edZoom=Math.max(1,Math.min(4,value));fitCanvas();$('#ed-zoom-fit').textContent=edZoom===1?'Fit':`${Math.round(edZoom*100)}%`;if(edZoom===1){$('.ed-canvas').scrollLeft=0;$('.ed-canvas').scrollTop=0}}
function syncVisualViewport(){const v=window.visualViewport;document.documentElement.style.setProperty('--visible-height',(v?.height||window.innerHeight)+'px');document.documentElement.style.setProperty('--visible-top',(v?.offsetTop||0)+'px');if(edPhoto&&!gesture)requestAnimationFrame(fitCanvas)}

let speech=null,speechStep=null,speechBusy=false,dictationBase='',dictationFinal='',dictationError='',dictationStarting=false;
function speechButtons(){const busy=speechBusy||dictationStarting;$('#dictation-start').disabled=busy||!(window.SpeechRecognition||window.webkitSpeechRecognition);$('#dictation-stop').disabled=!busy;$('#dictation-insert').disabled=busy;$('#dictation-target').disabled=busy;$('#dictation-text').readOnly=busy;$('#dictation-keyboard').disabled=busy}
function stopDictation(){if(speech)try{speech.stop()}catch{} }
function abortDictation(){if(speech)try{speech.abort()}catch{}speech=null;speechBusy=false;dictationStarting=false}
function joinSpokenText(original,added){const left=String(original||'').trimEnd(),right=String(added||'').trim();return right?left+(left?'\n':'')+right:left}
function appendDictationToStep(s,key,text){if(!['action','result',...Object.keys(extraDefs),'qualityChecks'].includes(key))throw Error('Unknown step field.');s[key]=joinSpokenText(s[key],text);const extra=key==='qualityChecks'?'quality':key;if(extraDefs[extra]&&!s.enabled.includes(extra))s.enabled.push(extra)}
function startDictation(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){$('#dictation-status').textContent='Use the microphone on your phone keyboard, or type into the transcript.';return}if(speechBusy||dictationStarting)return;
 dictationBase=$('#dictation-text').value.trim();dictationFinal='';dictationError='';const r=new R();speech=r;r.lang='en-GB';r.continuous=true;r.interimResults=true;r.maxAlternatives=1;dictationStarting=true;speechButtons();$('#dictation-status').textContent='Waiting for microphone permission…';
 r.onstart=()=>{if(speech!==r)return;dictationStarting=false;speechBusy=true;$('#dictation-status').textContent='Listening. Speak naturally, then tap Stop.';speechButtons()};
 r.onresult=e=>{if(speech!==r)return;const finals=[],interim=[];for(let i=0;i<e.results.length;i++){const result=e.results[i],text=result[0]?.transcript||'';(result.isFinal?finals:interim).push(text)}dictationFinal=finals.join(' ').trim();$('#dictation-text').value=[dictationBase,dictationFinal,interim.join(' ').trim()].filter(Boolean).join(' ')};
 r.onerror=e=>{if(speech!==r)return;dictationError=({'not-allowed':'Microphone access was not allowed. Enable it for this site, or use your keyboard microphone.','service-not-allowed':'Speech recognition is unavailable in this browser. Use the keyboard microphone.','audio-capture':'No microphone was found. Check the microphone connection.','network':'Speech recognition could not connect. Check your connection or use keyboard dictation.','no-speech':'No speech detected. Try again or use the keyboard microphone.','aborted':'Listening stopped.'})[e.error]||'Speech recognition stopped. Try again or use the keyboard microphone.';$('#dictation-status').textContent=dictationError};
 r.onend=()=>{if(speech!==r)return;speech=null;speechBusy=false;dictationStarting=false;$('#dictation-text').value=[dictationBase,dictationFinal].filter(Boolean).join(' ');$('#dictation-status').textContent=dictationError||'Listening stopped. Review and edit the transcript before adding it.';speechButtons()};
 try{r.start()}catch{speech=null;speechBusy=false;dictationStarting=false;$('#dictation-status').textContent='Could not start speech recognition. Use the keyboard microphone instead.';speechButtons()}
}
function initEnhancements(){
 normaliseChoices();syncVisualViewport();window.visualViewport?.addEventListener('resize',syncVisualViewport);window.visualViewport?.addEventListener('scroll',syncVisualViewport);
 $('#ed-zoom-in').onclick=()=>editorZoom(edZoom+.5);$('#ed-zoom-out').onclick=()=>editorZoom(edZoom-.5);$('#ed-zoom-fit').onclick=()=>editorZoom(1);$$('[data-nudge]').forEach(b=>b.onclick=()=>nudge(b.dataset.nudge));
 $('#edit-mark-note').onclick=()=>{const m=selMark();if(!m)return;const target=m.id,asText=['text','torque'].includes(m.type),dlg=$('#mark-text-dialog');$('#mark-text-title').textContent=asText?'Edit picture text':'Edit marker note';$('#mark-text-value').value=asText?(m.text||''):(m.note||'');dlg.showModal();$('#mark-text-value').focus();dlg.onclose=()=>{document.activeElement?.blur();if(dlg.returnValue==='save'&&edPhoto&&selected===target){change('note',()=>{const live=selMark();live[asText?'text':'note']=$('#mark-text-value').value});}$('#ed-done').focus({preventScroll:true});syncVisualViewport()}};
 $('#dictate-step').onclick=()=>{if(recording())return;speechStep=active().s;$('#dictation-target').value='action';$('#dictation-text').value='';$('#dictation-dialog').showModal();document.activeElement?.blur();$('#dictation-start').focus({preventScroll:true});$('#dictation-status').textContent=(window.SpeechRecognition||window.webkitSpeechRecognition)?'Tap Start listening to dictate.':'This browser does not offer web dictation. Tap Use keyboard microphone, then the microphone on your keyboard.';speechButtons()};
 $('#dictation-start').onclick=startDictation;$('#dictation-stop').onclick=()=>{stopDictation();$('#dictation-status').textContent='Finishing transcript…'};$('#dictation-dialog').onclose=()=>{abortDictation();speechStep=null};
 $('#dictation-keyboard').onclick=()=>{$('#dictation-status').textContent='Tap the microphone on your phone keyboard. If it is hidden, enable dictation in your device keyboard settings. You can also type here.';$('#dictation-text').focus()};
 $('#dictation-insert').onclick=()=>{if(speechBusy||dictationStarting)return;const text=$('#dictation-text').value.trim();if(!text){$('#dictation-status').textContent='Dictate or type some text first.';return}const target=speechStep;if(!project?.chapters.some(c=>c.steps.includes(target))){$('#dictation-status').textContent='The original step is no longer open. Copy the transcript before closing.';return}appendDictationToStep(target,$('#dictation-target').value,text);scheduleSave();$('#dictation-dialog').close();captureUI();toast('Text added. Check all values and units before use.')};
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')stopDictation()});
 $('#start-backup-import').onclick=importBackupFile;
 $('#backup-input').onchange=()=>{$('#backup-import-status').textContent=$('#backup-input').files[0]?.name||'No file selected.'};
}
async function importBackupFile(){const file=$('#backup-input').files[0],status=$('#backup-import-status');if(!file){status.textContent='Choose a saved draft (.json) first.';return}$('#start-backup-import').disabled=true;let count=0,last=null;try{if(file.size>400*1024*1024)throw Error('Backup is too large (400 MB limit).');const raw=JSON.parse(await file.text());const list=raw.format==='works-capture-library'?raw.manuals:[raw];if(!Array.isArray(list)||!list.length)throw Error('No manuals found in this backup. Use Import Word for .docx files.');const manuals=list.map(normalise);$('#backup-dialog').close();
 for(const m of manuals){const existing=await getManual(m.id);if(existing&&!await confirmAction('Manual already in library',`Replace “${m.details.title}” with this backup? Cancel keeps both as separate copies.`,'Replace')){m.id=uid();m.details.title+=' (imported copy)'}m.saveRev=Math.max(m.saveRev,((await getManual(m.id))?.saveRev||0)+1);await putManual(m);index[m.id]=await summary(m);count++;last=m.id}
 if($('#restore-choices').checked&&raw.configuration){mergeChoices(raw.configuration);await saveSettings()}await saveIndex();$('#lib-search').value='';if(manuals.length===1)await openManual(last);else await setPage('library');toast(`${count} saved draft(s) opened.`);
 }catch(e){const message=e instanceof SyntaxError?'This is not a valid JSON backup. For Word documents, choose Import Word.':e.message;status.textContent=message;if(!$('#backup-dialog').open)toast(`${count?count+' draft(s) imported. ':''}${message}`,10000)}finally{$('#start-backup-import').disabled=false}}
