'use strict';
/* Additional document structures. Capture and picture editing are shared. */
function askPageSetup(){return new Promise(resolve=>{const dlg=$('#page-setup-dialog');$('#new-paper').value='A4';$('#new-orientation').value='portrait';dlg.showModal();dlg.onclose=()=>resolve(dlg.returnValue==='create'?{paperSize:$('#new-paper').value,orientation:$('#new-orientation').value}:null)})}
function templateFrontUI(){let note=$('#import-source-note');if(!note){note=document.createElement('div');note.id='import-source-note';note.className='panel';$('#front-page').append(note)}note.hidden=!project.details.sourceFilename;note.textContent=project.details.sourceFilename?'Imported from '+project.details.sourceFilename+'. '+(project.details.importNotes||[]).join(' '):'';const type=project.details.documentType;$('#document-type-label').textContent=BUILTIN_TEMPLATES.find(t=>t.id===type)?.name||'Works Manual';for(const t of ['wm','twp','va'])$$('.'+t+'-only').forEach(e=>e.hidden=t!==type);$$('.non-va').forEach(e=>e.hidden=type==='va')}
function paperSettings(){const d=project.details,va=d.documentType==='va',size=va?d.paperSize:'A4',orientation=va?d.orientation:'portrait';const dims={A4:[11906,16838],A3:[16838,23811],A5:[8391,11906]}[size]||[11906,16838];return {size,orientation,width:orientation==='landscape'?dims[1]:dims[0],height:orientation==='landscape'?dims[0]:dims[1]}}
function applyPageSetup(){const p=paperSettings();$('#print-page-style').textContent=`@page {size:${p.size} ${p.orientation};margin:15mm} @media print {.paper {width:auto!important;max-width:none!important;min-height:0!important}.paper figure img{max-height:${Math.max(100,Math.round(p.height/15-220))}px}}`;const el=$('#document-preview');el.style.maxWidth=(p.width/p.height>1?1120:850)+'px';el.dataset.type=project.details.documentType}
function validateTables(tables){if(tables==null)return [];if(!Array.isArray(tables)||tables.length>30)throw Error('Invalid tables.');return tables.map(t=>{if(!t||!Array.isArray(t.headers)||!t.headers.length||t.headers.length>8||!Array.isArray(t.rows)||t.rows.length>100||t.rows.some(r=>!Array.isArray(r)||r.length!==t.headers.length))throw Error('Invalid table dimensions.');return {id:typeof t.id==='string'?t.id:uid(),headers:t.headers.map(String),rows:t.rows.map(r=>r.map(String))}})}
function tablesHTML(tables){return (tables||[]).map(t=>`<table class="content-table"><thead><tr>${t.headers.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v).replace(/\n/g,'<br>')}</td>`).join('')}</tr>`).join('')}</tbody></table>`).join('')}
function tableEditorUI(){const root=$('#table-editor'),s=active().s;s.tables??=[];root.hidden=false;
 root.innerHTML=`<div class="page-heading"><div><h2>Tables</h2><p class="hint">Edit cells below. Up to eight columns per table.</p></div><div class="row"><button id="paste-table">Paste from Excel</button><button id="add-table">＋ Table</button></div></div>`+s.tables.map((t,i)=>`<div class="table-block"><div class="row"><b>Table ${i+1}</b><button data-add-row="${i}" ${t.rows.length>=100?'disabled':''}>＋ Row</button><button data-add-col="${i}" ${t.headers.length>=8?'disabled':''}>＋ Column</button><button data-del-table="${i}" class="danger-text">Delete table</button></div><div class="table-scroll"><table><thead><tr>${t.headers.map((v,j)=>`<th><input aria-label="Table ${i+1} column ${j+1} heading" data-cell="${i},-1,${j}" value="${esc(v)}"><button data-del-col="${i},${j}" aria-label="Remove column ${j+1}" ${t.headers.length===1?'disabled':''}>Remove column</button></th>`).join('')}<th></th></tr></thead><tbody>${t.rows.map((r,k)=>`<tr>${r.map((v,j)=>`<td><textarea aria-label="Table ${i+1} row ${k+1} column ${j+1}" rows="2" data-cell="${i},${k},${j}">${esc(v)}</textarea></td>`).join('')}<td><button data-del-row="${i},${k}" aria-label="Remove row ${k+1}">×</button></td></tr>`).join('')}</tbody></table></div></div>`).join('');
 const update=()=>{scheduleSave();tableEditorUI()};$('#paste-table').onclick=()=>pasteExcelTable(s);$('#paste-table').disabled=s.tables.length>=30;$('#add-table').disabled=s.tables.length>=30;$('#add-table').onclick=()=>{s.tables.push({id:uid(),headers:['Heading','Detail'],rows:[['','']]});update()};
 root.querySelectorAll('[data-cell]').forEach(e=>e.oninput=()=>{const [i,r,c]=e.dataset.cell.split(',').map(Number);(r===-1?s.tables[i].headers:s.tables[i].rows[r])[c]=e.value;scheduleSave()});
 for(const [attr,fn] of [['add-row',i=>s.tables[i].rows.push(s.tables[i].headers.map(()=>''))],['add-col',i=>{s.tables[i].headers.push('Heading');s.tables[i].rows.forEach(r=>r.push(''))}]])root.querySelectorAll('[data-'+attr+']').forEach(b=>b.onclick=()=>{fn(+b.getAttribute('data-'+attr));update()});
 for(const attr of ['del-table','del-col','del-row'])root.querySelectorAll('[data-'+attr+']').forEach(b=>b.onclick=async()=>{if(!await confirmAction('Remove table content?','This removes the selected table, column or row.','Remove'))return;const [i,j]=b.getAttribute('data-'+attr).split(',').map(Number);if(attr==='del-table')s.tables.splice(i,1);else if(attr==='del-col'){s.tables[i].headers.splice(j,1);s.tables[i].rows.forEach(r=>r.splice(j,1))}else s.tables[i].rows.splice(j,1);update()});
}
function trainingRows(d){const cols=[d.trainingBy,d.trainingDates,d.operators].map(x=>String(x||'').split('\n'));return Array.from({length:Math.max(...cols.map(x=>x.length))},(_,i)=>cols.map(c=>c[i]||''))}
function twpControlRows(d){return [['Ref',d.number,'Version',d.revision,'Author',d.author],['Factory location',d.line,'Start date',ukDate(d.startDate),'End date',ukDate(d.endDate)],['Production approval',d.productionName,'Date',ukDate(d.productionDate),'',''],['Quality approval',d.qualityName,'Date',ukDate(d.qualityDate),'','']]}
async function previewSpecial(){const d=project.details,va=d.documentType==='va',counter={n:0},gaps=missing();$('#review-alert').textContent=gaps.length?`${gaps.length} item(s) need confirmation: ${gaps.slice(0,5).join(' · ')}`:'Ready for engineering review.';$('#review-alert').classList.toggle('ok',!gaps.length);
 let h=`<div class="doc-header"><div>${va?`<b>Title: ${esc(d.title)}</b><br>Author: ${esc(d.author)}<br>ID Number: ${esc(d.number)} · Release Date: ${esc(ukDate(d.date))}`:'<b>MANUFACTURING ENGINEER<br>TEMPORARY WORK PROCEDURE</b>'}</div><img src="${symById('logo').src}" alt="Brompton"></div>`;
 if(settings.draftMark!==false)h+='<p class="pending">DRAFT — NOT APPROVED FOR OPERATION</p>';
 if(va&&(d.safety||d.advisory||d.hazards.length||d.mandatory.length||d.quality||d.qualityChecks)){h+=para(d.safety)+para(d.advisory);h+='<div class="twp-symbols">'+[...d.hazards,...d.mandatory].map(id=>`<img src="${symById(id).src}" alt="${esc(symById(id).label)}">`).join('')+'</div>';if(d.quality||d.qualityChecks)h+=qualityHTML(d.quality,d.qualityChecks)}
 if(!va){h+=tablesHTML([{headers:['Ref','Version','Author'],rows:[[d.number,d.revision,d.author]]}])+`<p><i>This is a Temporary Work Procedure to be used when performing the following operation:</i></p><h2 class="operation-title">${esc(d.title)}</h2>`+tablesHTML([{headers:['Factory location','Start date','End date'],rows:[[d.line,ukDate(d.startDate),ukDate(d.endDate)]]},{headers:['Approval','Name','Date'],rows:[['Production',d.productionName,ukDate(d.productionDate)],['Quality',d.qualityName,ukDate(d.qualityDate)]]},{headers:['Training Conducted by:','Dates:','Operator Names:'],rows:trainingRows(d)}]);
 h+=`<p class="training-note">ONLY the trained persons identified above are to perform the following procedures:</p><p><b>Instruction:</b> ${esc(d.instructionKind)} · ${esc(d.affectedManuals)}</p><p><b>Risk Assessment:</b> ${esc(d.risk)}</p><h2>Overview</h2>${para(d.overview)}<h2>Health &amp; Safety</h2>${para(d.safety)}<div class="twp-symbols">${[...d.hazards,...d.mandatory].map(id=>`<img src="${symById(id).src}" alt="${esc(symById(id).label)}">`).join('')}</div>${para(d.advisory)}<h2>Quality</h2>${qualityHTML(d.quality,d.qualityChecks)}`;
 if(d.cover)h+=await figureHTML(d.cover,++counter.n,'Overview');if(d.workspace)h+=await figureHTML(d.workspace,++counter.n,'Workspace');h+='<h2 class="chap">PROCEDURE</h2>';
 }else {if(d.cover)h+=await figureHTML(d.cover,++counter.n,'Visual aid');if(d.workspace)h+=await figureHTML(d.workspace,++counter.n,'Workspace');}
 for(const [i,c] of project.chapters.entries()){h+=`<h2 class="${i?'chap':''}">${esc(c.title)}</h2>`;for(const s of c.steps)h+=await stepHTML(c,s,counter)}$('#document-preview').innerHTML=h;
}
async function buildSpecialWord(){if(!window.docx)throw Error('Word exporter did not load.');await symbolsReady;
 const D=window.docx,d=project.details,va=d.documentType==='va',ps=paperSettings(),cw=ps.width-1700;
 const T=(s,o={})=>new D.TextRun({text:String(s??''),...o}),P=(s='',o={})=>new D.Paragraph({children:Array.isArray(s)?s:[typeof s==='string'?T(s):s],spacing:{after:100},...o});
 const H=(s,o={})=>P(T(s,{bold:true,size:25}),{keepNext:true,spacing:{before:200,after:100},...o});
 const border={style:D.BorderStyle.SINGLE,size:6,color:'333333'},borders={top:border,bottom:border,left:border,right:border};
 const table=(headers,rows)=>new D.Table({width:{size:cw,type:D.WidthType.DXA},columnWidths:headers.map(()=>Math.floor(cw/headers.length)),rows:[headers,...rows].map((r,i)=>new D.TableRow({tableHeader:i===0,children:r.map(v=>new D.TableCell({borders,width:{size:Math.floor(cw/headers.length),type:D.WidthType.DXA},margins:{top:70,bottom:70,left:100,right:100},shading:i===0?{fill:'EEEEEE'}:undefined,children:String(v||'').split('\n').map(l=>P(T(l,{bold:i===0}),{spacing:{after:40}}))}))}))});
 const image=(src,w,h,alt)=>new D.ImageRun({type:src.startsWith('data:image/png')?'png':'jpg',data:dataBytes(src),transformation:{width:Math.round(w),height:Math.round(h)},altText:{title:alt,description:alt,name:alt}});
 let fig=0;const figure=async(p)=>{const scale=Math.min((cw/15-20)/p.width,(ps.height/15-230)/p.height,1),cap=`Fig. ${++fig}${p.caption?' — '+p.caption:''}`;return [P(image(await markedImage(p),p.width*scale,p.height*scale,p.caption||'Picture'),{alignment:D.AlignmentType.CENTER,keepNext:true}),P(T(cap,{size:18,color:'2B579A'}),{alignment:D.AlignmentType.CENTER}),...p.marks.filter(m=>m.note||m.type==='number').map(m=>P(`${m.number?m.number+'. ':''}${m.note||'REQUIRES ENGINEER CONFIRMATION'}`))]};
 const out=[],logo=symById('logo');
 if(settings.draftMark!==false)out.push(P(T('DRAFT — NOT APPROVED FOR OPERATION',{color:'9B4328',bold:true,size:18})));
 if(!va){out.push(H('MANUFACTURING ENGINEER'),H('TEMPORARY WORK PROCEDURE'),table(['Ref','Version','Author'],[[d.number,d.revision,d.author]]),P(''),P(T('This is a Temporary Work Procedure to be used when performing the following operation:',{italics:true})),H(d.title),table(['Factory location','Start date','End date'],[[d.line,ukDate(d.startDate),ukDate(d.endDate)]]),P(''),table(['Approval','Name','Date'],[['Production',d.productionName,ukDate(d.productionDate)],['Quality',d.qualityName,ukDate(d.qualityDate)]]),P(''),table(['Training Conducted by:','Dates:','Operator Names:'],trainingRows(d)),P(T('ONLY the trained persons identified above are to perform the following procedures:',{color:'0070C0',bold:true})),P(`Instruction: ${d.instructionKind}   ${d.affectedManuals}`),P(`Risk Assessment: ${d.risk}`),H('Overview'),P(d.overview),H('Health & Safety'),...lines(d.safety).map(l=>P(l)));
 const syms=[...d.hazards,...d.mandatory].map(symById);for(let i=0;i<syms.length;i+=4)out.push(P(syms.slice(i,i+4).flatMap(s=>[image(s.src,80,80*s.h/s.w,s.label),T('  ')])));if(d.advisory)out.push(P(d.advisory));
 out.push(H('Quality Points'),P(d.quality),...lines(d.qualityChecks).map(l=>P(l,{bullet:{level:0}})));if(d.cover)out.push(...await figure(d.cover));if(d.workspace)out.push(...await figure(d.workspace));out.push(H('PROCEDURE',{pageBreakBefore:true}));
 }else {if(d.safety)out.push(H('Safety Points'),P(d.safety));if(d.advisory)out.push(P(d.advisory));const syms=[...d.hazards,...d.mandatory].map(symById);for(let i=0;i<syms.length;i+=4)out.push(P(syms.slice(i,i+4).flatMap(x=>[image(x.src,65,65*x.h/x.w,x.label),T(' ')])));if(d.quality||d.qualityChecks)out.push(H('Quality Points'),P(d.quality),...lines(d.qualityChecks).map(l=>P(l,{bullet:{level:0}})));if(d.cover)out.push(...await figure(d.cover));if(d.workspace)out.push(...await figure(d.workspace));}
 for(const [ci,c] of project.chapters.entries()){out.push(H(c.title,{pageBreakBefore:ci>0}));for(const [si,s] of c.steps.entries()){
 out.push(H(`${va?'':`${ci+1}.${si+1}  `}${s.title}`));if(s.action)out.push(...String(s.action).split('\n').map(l=>P(l)));if(s.result)out.push(P([T('Check: ',{bold:true}),T(s.result)]));
 for(const k of s.enabled){const color={safety:'FF0000',quality:'00B050',support:'0070C0'}[k]||'111111';out.push(P(T(k==='quality'?'Quality Points':extraDefs[k][0],{bold:true,color}),{keepNext:true}),P(s[k]||'REQUIRES ENGINEER CONFIRMATION'));if(k==='quality')out.push(...lines(s.qualityChecks).map(l=>P(l,{bullet:{level:0}})));if(k==='safety'&&s.ppe.length)out.push(P(s.ppe.map(symById).flatMap(x=>[image(x.src,55,55*x.h/x.w,x.label),T(' ')])))}
 for(const p of s.photos)out.push(...await figure(p));for(const t of s.tables||[])out.push(table(t.headers,t.rows),P(''));for(const m of s.media)out.push(P(T(`Recording: ${m.name} — ${m.note||'See editable backup'}`,{italics:true,size:18})));
 }}
 const header=new D.Header({children:[P([T(va?`Title: ${d.title}`:d.title,{bold:true,size:18})]),P([T(va?`Author: ${d.author}   ID Number: ${d.number}   Release Date: ${ukDate(d.date)}`:d.number,{size:16})],{keepNext:true}),P(image(logo.src,135,135*logo.h/logo.w,'Brompton'),{alignment:D.AlignmentType.RIGHT,border:{bottom:border}})]});
 const footer=new D.Footer({children:[P(new D.TextRun({children:['Page ',D.PageNumber.CURRENT,' of ',D.PageNumber.TOTAL_PAGES],size:16}),{alignment:D.AlignmentType.CENTER})]});
 return D.Packer.toBlob(new D.Document({creator:d.author||'Works Capture',title:d.title,styles:{default:{document:{run:{font:'Arial',size:20}}}},sections:[{properties:{page:{size:{width:Math.min(ps.width,ps.height),height:Math.max(ps.width,ps.height),orientation:ps.orientation==='landscape'?D.PageOrientation.LANDSCAPE:D.PageOrientation.PORTRAIT},margin:{top:1900,bottom:850,left:850,right:850,header:350,footer:350}}},headers:{default:header},footers:{default:footer},children:out}]}));
}
